-- =============================================================
-- SAD Laboratory Exercise 3 — Supabase Setup Script
-- Run this in Supabase: Dashboard -> SQL Editor -> New Query
-- =============================================================

-- 1. Create the table
CREATE TABLE service_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_name TEXT NOT NULL,
  department TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  priority TEXT NOT NULL,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id)
);

-- 2. Enable Row Level Security
ALTER TABLE service_requests ENABLE ROW LEVEL SECURITY;

-- 3. Policies
-- All authenticated users can VIEW all requests
CREATE POLICY "Authenticated users can view requests"
ON service_requests
FOR SELECT
TO authenticated
USING (true);

-- Authenticated users can INSERT only rows tagged with their own user_id
CREATE POLICY "Authenticated users can insert requests"
ON service_requests
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Authenticated users can UPDATE only their own requests
CREATE POLICY "Authenticated users can update requests"
ON service_requests
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

-- Authenticated users can DELETE only their own requests
CREATE POLICY "Authenticated users can delete requests"
ON service_requests
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- 4. (Optional) Seed a few sample rows for testing.
-- Replace 'YOUR-TEST-USER-UUID' with an actual auth.users.id after you
-- create a test account in Authentication -> Users.
-- INSERT INTO service_requests (requester_name, department, category, description, priority, user_id)
-- VALUES
--   ('Juan Dela Cruz', 'Registrar', 'Network Problem', 'Computer cannot connect to university Wi-Fi.', 'High', 'YOUR-TEST-USER-UUID'),
--   ('Ana Santos', 'Library', 'Printer Problem', 'Printer in circulation desk is jammed.', 'Medium', 'YOUR-TEST-USER-UUID');
